---
- name: Playbook with variables demo
  hosts: linuxhosts
  vars:
    - var1: zig
    - var2: zag
  tasks:
    - name: print data
      shell: echo "{{var1}}" when you should "{{zag}}" > /home/takeoff/vars.txt
